services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: apply-digital-test:latest
    container_name: apply-digital-app
    environment:
      - PORT=${PORT}
      - POSTGRES_HOST=db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - JWT_TOKEN=${JWT_TOKEN}
      - CDN_BASE_URL=${CDN_BASE_URL}
      - AD_SPACE_ID=${AD_SPACE_ID}
      - AD_ENVIRONMENT_ID=${AD_ENVIRONMENT_ID}
      - AD_ACCESS_TOKEN=${AD_ACCESS_TOKEN}
      - AD_CONTENT_TYPE_ID=${AD_CONTENT_TYPE_ID}
    ports:
      - '3000:3000'
    depends_on:
      db:
        condition: service_started

  db:
    image: postgres:16-alpine
    container_name: apply-digital-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    driver: local
