services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: apply-digital-test:latest
    container_name: apply-digital-app
    environment:
      - PORT=${PORT}
      - DATABASE_HOST=db
      - DATABASE_USER=${POSTGRES_USER}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_NAME=${POSTGRES_DB}
      - DATABASE_PORT=${POSTGRES_PORT}
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_started

  db:
    image: postgres:16-alpine
    container_name: apply-digital-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    driver: local
